/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.baohanh;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BaoHanh;

/**
 *
 * @author nguyentrikhoi
 */
public class DanhSachSPBaoHanh extends javax.swing.JDialog {

    private GiaoDienBaoHanh gdBH = new GiaoDienBaoHanh();

    /**
     * Creates new form DanhSachSPBaoHanh
     */
    public DanhSachSPBaoHanh(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    public void fillToTableSPBH(List<BaoHanh> lstbh) {
        DefaultTableModel model = (DefaultTableModel) tbl_SanPhamBaoHanh.getModel();
        model.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (BaoHanh bh : lstbh) {
            Date thoiHanBaoHanh = bh.getIDSerialNumber().getThoiGianBaoHanh();
            Date ngayMua = bh.getIDHoaDonChiTiet().getNgayTao();
            String formattedDate = sdf.format(thoiHanBaoHanh);
            String formattedDate2 = sdf.format(ngayMua);
            model.addRow(new Object[]{ bh.getIDHoaDonChiTiet().getIDHoaDonChiTiet(), bh.getIDSerialNumber().getIDSerialNumber(),bh.getIDSanPham().getIDSanPham(),bh.getIDSanPham().getTenSanPham(), formattedDate,formattedDate2 ,bh.getIDSerialNumber().getTrangThai() ? "Còn Bảo Hành" : "Hết Hạn Bảo Hành"});
        }
    }

    public String SanPhamDCBaoHanh() {
        int index = tbl_SanPhamBaoHanh.getSelectedRow();
        String maSanPham = null;
        if (index == -1) {
            return null;
        }
        String trangThaiBaoHanh = tbl_SanPhamBaoHanh.getValueAt(index, 6).toString();
        if (trangThaiBaoHanh.equals("Hết Hạn Bảo Hành")) {
            JOptionPane.showMessageDialog(this, "Sản phẩm đã hết hạn không được chọn.");
            tbl_SanPhamBaoHanh.clearSelection();

        } else {
            maSanPham = tbl_SanPhamBaoHanh.getValueAt(index, 2).toString();
        }
        return maSanPham;
    }
    public String HDCTBaoHanh() {
        int index = tbl_SanPhamBaoHanh.getSelectedRow();
        String maHDCT = null;
        if (index == -1) {
            return null;
        }
        String trangThaiBaoHanh = tbl_SanPhamBaoHanh.getValueAt(index, 6).toString();
        if (trangThaiBaoHanh.equals("Hết Hạn Bảo Hành")) {
            return null;

        } else {
            maHDCT = tbl_SanPhamBaoHanh.getValueAt(index, 0).toString();
        }
        return maHDCT;
    }
    
       public String SeriBaoHanh() {
        int index = tbl_SanPhamBaoHanh.getSelectedRow();
        String maSeri = null;
        if (index == -1) {
            return null;
        }
        String trangThaiBaoHanh = tbl_SanPhamBaoHanh.getValueAt(index, 6).toString();
        if (trangThaiBaoHanh.equals("Hết Hạn Bảo Hành")) {
            return null;

        } else {
            maSeri = tbl_SanPhamBaoHanh.getValueAt(index, 1).toString();
        }
        return maSeri;
    }
    public String layTenSanPhamDaChon() {
        return SanPhamDCBaoHanh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        background1 = new view.until.swing.Background();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_SanPhamBaoHanh = new javax.swing.JTable();
        btn_Chon = new view.until.button.Button();
        btn_Huy = new view.until.button.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 24, 32));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 231, 21));
        jLabel1.setText("Danh Sách Sản Phẩm Bảo Hành");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tbl_SanPhamBaoHanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hoá Đơn Chi Tiết", "Mã Seri Sản Phẩm", "Mã Sản Phẩm", "Tên Sản Phẩm", "Thời Hạn Bảo Hành", "Ngày Mua", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_SanPhamBaoHanh.getTableHeader().setReorderingAllowed(false);
        tbl_SanPhamBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_SanPhamBaoHanhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_SanPhamBaoHanh);

        btn_Chon.setText("Chọn");
        btn_Chon.setColor1(new java.awt.Color(16, 24, 32));
        btn_Chon.setColor2(new java.awt.Color(254, 231, 21));
        btn_Chon.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btn_Chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.setColor1(new java.awt.Color(16, 24, 32));
        btn_Huy.setColor2(new java.awt.Color(254, 231, 21));
        btn_Huy.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251)
                .addComponent(btn_Chon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Chon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonActionPerformed
//        SanPhamDCBaoHanh();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ChonActionPerformed

    private void tbl_SanPhamBaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_SanPhamBaoHanhMouseClicked
        SanPhamDCBaoHanh();
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_SanPhamBaoHanhMouseClicked

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachSPBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachSPBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachSPBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachSPBaoHanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DanhSachSPBaoHanh dialog = new DanhSachSPBaoHanh(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.until.swing.Background background1;
    private view.until.button.Button btn_Chon;
    private view.until.button.Button btn_Huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_SanPhamBaoHanh;
    // End of variables declaration//GEN-END:variables
}
